services:
  server: 
    container_name: group.kalmykov.server
    image: server
    build:
      context: .
      dockerfile: Server/Dockerfile


  certbot:
    container_name: group.kalmykov.certbot 
    env_file:
      - .env
    volumes:
      - 'ssl_share_dir:${SSL_DIR}'
    build:
      context: ./.docker/certbot
      dockerfile: Dockerfile 


  nginx:
    container_name: group.kalmykov.nginx
    image: nginx
    depends_on:
      - certbot
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile 
    env_file:
      - .env
    volumes:
      -  ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf 
      - 'ssl_share_dir:${SSL_DIR}' 
    ports:
      -  "80:80"
      - "443:443"

volumes:
  ssl_share_dir:
 




