services:
  server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro    
  nginx:
    env_file:
      - .env 
    environment:
      - NGINX_DOMAIN_NAMES=${NGINX_DOMAIN_NAMES}
      - SSL_FILE_CHAIN=${SSL_FILE_CHAIN}
      - SSL_FILE_KEY=${SSL_FILE_KEY}
    volumes:
      -  ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf 
      - /etc/letsencrypt/live/kalmykov.group:${SSL_DIR}
    ports:
      -  "80:80"
      - "443:443"


