services:  
  nginx:
    env_file:
      - .env 
    environment:
      - NGINX_DOMAIN_NAMES=${NGINX_DOMAIN_NAMES}
      - SSL_FILE_CHAIN=${SSL_FILE_CHAIN}
      - SSL_FILE_KEY=${SSL_FILE_KEY}
    volumes:
      -  ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf 
      - /etc/letsencrypt/live/kalmykov.group:${SSL_DIR}
    ports:
      -  "80:80"
      - "443:443"


